import { useState, useEffect, useRef } from "react";
import { generateConsequences } from "../services/forensics";
import { useToast } from "../context/ToastContext";

export default function TriageMode({ tasks, onDeprioritize }) {
  const { addToast } = useToast();
  const [consequences, setConsequences] = useState({});
  const [loading, setLoading] = useState(false);
  const hasFetchedRef = useRef(false); // FIX: prevent re-fetching on every task change

  // Find active tasks due in the next 48 hours
  const now = new Date();
  const fortyEightHoursFromNow = new Date(now.getTime() + 48 * 60 * 60 * 1000);

  const crisisTasks = tasks.filter((t) => {
    if (t.status === "completed") return false;
    if (!t.deadline) return false;
    const deadlineDate = t.deadline.toDate ? t.deadline.toDate() : new Date(t.deadline);
    return deadlineDate >= now && deadlineDate <= fortyEightHoursFromNow;
  });

  // FIX: threshold corrected to 16h (matches the UI label)
  const totalHours = crisisTasks.reduce((sum, t) => sum + (t.estimatedHours || 0), 0);
  const isOverloaded = totalHours > 16;
  const currentTaskIds = crisisTasks.map(t => t.id).sort().join(",");

  // FIX: only fetch consequences once per triage session, not on every task update
  useEffect(() => {
    if (!isOverloaded || crisisTasks.length === 0) {
      hasFetchedRef.current = false; // reset when triage clears
      return;
    }
    if (hasFetchedRef.current) return; // already fetched this session
    
    async function loadConsequences() {
      hasFetchedRef.current = true;
      setLoading(true);
      try {
        const map = await generateConsequences(crisisTasks);
        setConsequences(map);
      } catch (err) {
        console.error("Failed to generate consequences:", err);
        hasFetchedRef.current = false; // allow retry on error
      } finally {
        setLoading(false);
      }
    }

    loadConsequences();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOverloaded, currentTaskIds]);

  if (!isOverloaded) return null;

  return (
    <div className="bg-rose-950/20 border border-rose-500/40 shadow-xl shadow-rose-950/5 rounded-3xl p-5 sm:p-6 mb-8 relative overflow-hidden">
      {/* Side Color Alert Accent */}
      <div className="absolute top-0 bottom-0 left-0 w-1.5 bg-rose-500 animate-pulse" />

      <div className="flex flex-col gap-4">
        {/* Warning Title */}
        <div className="flex items-center gap-3">
          <div className="bg-rose-500/10 p-2.5 rounded-xl border border-rose-500/20 text-rose-400 animate-bounce">
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
          </div>
          <div>
            <h4 className="text-sm font-bold text-rose-450 uppercase tracking-wider">
              Crisis Triage Mode Activated
            </h4>
            <p className="text-xs text-rose-400/80 mt-0.5">
              Workload exceeds safe limits. You have {totalHours.toFixed(1)}h due in the next 48h (limit is 16h).
            </p>
          </div>
        </div>

        <p className="text-xs text-slate-350 leading-relaxed font-semibold">
          You cannot complete all of this on time. Review the consequence map generated by DeadlineIQ and select tasks to postpone by 7 days.
        </p>

        {/* Consequence Map Table */}
        <div className="mt-2 space-y-3.5 bg-slate-950/50 p-4 border border-slate-900 rounded-2xl">
          <div className="text-[10px] font-bold text-slate-500 uppercase tracking-widest border-b border-slate-800/40 pb-2">
            AI Consequence Mapping
          </div>

          {loading ? (
            <div className="py-8 flex flex-col items-center justify-center gap-2">
              <svg className="animate-spin h-5 w-5 text-rose-400" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
              </svg>
              <span className="text-[10px] font-bold text-slate-400 animate-pulse uppercase tracking-wider">Calculating Impact Map...</span>
            </div>
          ) : (
            <div className="space-y-3">
              {crisisTasks.map((task) => (
                <div 
                  key={task.id} 
                  className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-slate-950/80 border border-slate-850 p-3 rounded-xl"
                >
                  <div className="flex-1">
                    <div className="flex items-center gap-2">
                      <span className="text-xs font-bold text-slate-200">{task.title}</span>
                      <span className="text-[9px] bg-slate-900 text-slate-450 border border-slate-800 px-2 py-0.5 rounded font-bold">
                        {task.estimatedHours}h
                      </span>
                    </div>
                    <p className="text-[11px] text-slate-400 italic mt-1 font-semibold leading-relaxed">
                      Consequence: {consequences[task.id] || "Calculating..."}
                    </p>
                  </div>
                  
                  <button
                    onClick={() => {
                      onDeprioritize(task);
                      addToast(`Postponed "${task.title}" by 7 days.`, { type: "success" });
                    }}
                    className="px-3.5 py-1.5 rounded-lg bg-rose-950/60 hover:bg-rose-900 border border-rose-500/30 hover:border-rose-500/50 text-rose-300 font-bold text-[10px] uppercase tracking-wider transition shrink-0 self-start sm:self-center"
                  >
                    Postpone 7 Days
                  </button>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
